### ISSUE TITLE
Arm Horgue job

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#115]
Actually, Horgue didn't find his place on the game. 

I propose to turn it into long range AA. (1200range)

**Comment by ksilversurfer** [comment]
LOL?

**Comment by ksilversurfer** [comment]
seems when should be op air?

**Comment by ZweisteinT** [comment]
Hi,

yes horgue suck. But i think its only because of the wide spread. In most cases you cant apply any damage on the enemy. I think we should just lower spread. 

A mobile long range aa is a new concept. It would allow to hit fighter screens more easy -> huge game impact. In that sense, every race would need such a mobile longe range aa to make it balanced. 

But i vote for the lower spread for now.

**Comment by skymyj** [comment]
I have maybe a New Idea : Long Range EMP Missile :)
could be Op, but I'm thinking it could be nice !

**Comment by ksilversurfer** [comment]
ohh that is actually good idea skymyj, becouse core has mobile tactical nuke, but arm nothing simillar
