### ISSUE TITLE
Cost for All T2

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#222]
From History, Arm / Core T2 cost a lot resources. Tll nothing.
So we have increase TLL cost T2 Cons to balance.

Just to have discussion, what about decrease all cost now ? 
Like 1K metal for All T2 vs 2.5/3K actually ?
This change means that we should decrease too the T1.5 Cons to 250m vs 800m today.

My opinion is to not change this balance, but there is no sense actually to have 3k for T2 cons.

**Comment by Antarac** [comment]
Just a few days ago i thought about that and figured out
for myself that it might be better with expensive Cons.

It feels like since ever T2 in TA was more expensive than in BA.
People needed to get used to it when they change from BA to TA.
And it is an accepted feature.
To change it now means to force people to get again used to BA state.
Could be taken like it was shitty idea to make it more
expensive and now get back to BA cost setup.

But actually it seems to be a intelligent change.
Start to early with T2 units or the more expensive T2 Eco can make you loose.
This way it makes T1 more important in beginning of game.
Counts for combat units and economy.
Cant be wrong to need 10-20 T1 buildings before going T2.
Good balanced in TA cause units dont get quickly worthless when Higher Tech Level comes.
The T2 Con itself gets a strategic target due to costs instead being mass Product.
Overall more "Character" or reason to exist for units the way it is now.

Since i dont know much about TLL i can only tell that i dont mind if they have cheaper T2 Con.
TLL is different in many ways so why not this advance.

**Comment by skymyj** [comment]
Thanks for your comment Antarac and for your good english. You place the good words. Maybe we could start a little decrease of all t2 construction veh. Actually tll are 15% cheaper. Now with overcharged extractor there is no reasonto keep this diffrence. 

I propose so, 30% decrease for Arm and Core and 15% for tll to have a cost at 2k metal.

**Comment by ksilversurfer** [comment]
100% agree here T2 constructors are way too expensive.

**Comment by nixtux** [comment]
+1 from me if you add some originality back, for example all t2 kbot cons have the same cost

**Comment by nixtux** [comment]
Eg
http://imolarpg.dyndns.org/trac/balatest/browser/branches/BAR/units/armack.lua
http://imolarpg.dyndns.org/trac/balatest/browser/branches/BAR/units/corack.lua

**Comment by skymyj** [comment]
Tomorrow, i will fix all t2 cons

**Comment by skymyj** [comment]
#250

**Comment by Finkky** [comment]
I would be careful with Tll t2 alignment with Cor/Arm, as far as I remember Tll is lacking T1.5 which is why their t2 _was_ meant more like a T1,8 which could be advanced to earlier and give the faction some advantage in midgame and also add to variety of used strategies.

**Comment by nixtux** [comment]
Well if its 'as far as I remember' I suggest you come and play xD, hi btw how's you?

**Comment by ksilversurfer** [comment]
Hello Finkky !!!!!
Come play Finkky we miss you man ! :))

**Comment by skymyj** [comment]
Finkky. There  were so many changes. You should come back.
Now tll have many new stuff

**Comment by skymyj** [comment]
I will apply the 25% decrease cost and maxdamage for all T2. Before begin, Nix does you agree ? 
Thanks.

**Comment by skymyj** [comment]
I will apply the 35% decrease cost and maxdamage for all T2. Before begin, Nix does you agree ?
Thanks.

**Comment by Antarac** [comment]
What do you mean with maxdamage? In this Issue only cost were discussed.

**Comment by skymyj** [comment]
Cause, they cons have OP HP cause of their initial high cost. 
Was a protection versus invest.
So it's logic to decrease Maxdamage too

**Comment by Antarac** [comment]
I see.
And why 35% for all?
You wrote earlier:
"I propose so, 30% decrease for Arm and Core and 15% for tll to have a cost at 2k metal."

**Comment by skymyj** [comment]
Cause, to have a cost at 2k metal, it's 35% and not 30% for vehicle.

**Comment by Antarac** [comment]
I see.
And how about this you posted:
"I propose so, 30% decrease for Arm and Core and 15% for tll to have a cost at 2k metal."

**Comment by nixtux** [comment]
I'm not happy about addition of t2 nano, it will remove the meta game of needed low tech unit or engineers to rebuild them

**Comment by skymyj** [comment]
We just add an option for players. 
It's the same for the T4 Nano with Cons Ship => If you have not many Nano, you build T4 Nano. Or if you have a lot, you morph the T3 into T4. It's same here.
Engineers make weapon structures instead of T2.  So, they will again used

**Comment by skymyj** [comment]
Antarac. We had already discuss with silver. An you were for this feature.
 It's just a proposition. Now I do it to have less work and not wait 2 months for merging request, then reopen other with nano or forget it. 
I know it's not the good way but I think it concerns just few changes. You just have to think 1 thing more : 1 nano.m for t2. 
Now i can delete it.

**Comment by Antarac** [comment]
Yes, we discussed Nanos with Silver. But it was in Chat and nobody knows about it.
I think i offered to make a Issue about it, so it would be postet since 2 weeks already.
Now comes a new meaning from Nixtux which should be heared too.

Also i do not understand where you got the 35% from and how it works with different TLL cost.
Is it also the result of chat or did you decide it or is it the average of the Issue?

In this case i have simply not enough info to make good comments or votes.

I only try to do my best and work like Nixtux asked for it in #294 

You guys do all the major work like programming, modeling, etc since many years.
I make only Issues and Comments since short time.
So of course you can do it how you like.
No need to delete something mate.

**Comment by skymyj** [comment]
The 35% is a test. Maybe we have to decrease at 50% or 25%. 
The only think I know, that at 35%, we have 2K for vehicle metal cost. And it's a psychological barrier.
We have the chance to make revert or add other changes with no real threat

**Comment by Antarac** [comment]
Allright, im fine with metal cost and HP change.

Nixtux' mentioned that T1 Cons get useless with adding of the T2 Nano to T2 Cons.
I like the Idea to add T2 Nano but Nixtux is right.
In later game you need T1 Cons basically only for Nanos.
Better we don't add T2 Nano.

**Comment by skymyj** [comment]
So, If I follow your logic, in later game, T1 are useless. And ?
In later game, did you use medium t1 tank, t1 artillery, solar t1 or wind ?
It's logic than you will not use the t1 units after 45min games.
So, I don't understand why did you have afraid to not use them ?

**Comment by Antarac** [comment]
Seems to be a good thing if T1 units
are still needed in long games.
I see good reasons on both sides.
Hard to tell.

**Comment by skymyj** [comment]
It will depends of player meta games. 
The T1 are cheap Vs T2. And they always will be made by players. Even after 45min.
