### ISSUE TITLE
Jumping coms

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#232]
Suggestion: - remove jump from coms or make jumpjet very expensive
 
Jumping coms are crazy OP, some good players using that trick even vs weak players.
Also using jump feature is not easy for newbies, thats why mostly pro players sending jumping coms.

**All units that can jump should be able to jump without jumpjet - to be easier for players.**

**Jumping OP coms should be rebalanced (make expensive jumpjet) or remove jump from coms...**

**Comment by Antarac** [comment]
I would not delete it since its a really great feature.
I got killed that way and i only wanted to learn it too!
No bad feelings since feature is so cool ;)

Jump button is on second command page.
Since switching the command pages before jumping
can fail badly with Commander Invisibility, timing
and dgun shooting while you under pressure to
manage all that.
Easy to click jump button on first command
page  would make more people able to do
nice Jumps.

You could also make smaller jump radius but its already quiet small in my opinion.

I dont even know if jump robots need that building to jump but
i think it should be only for commander jump as you said.

To make jump building more expensive is ok i think but it wont help against "cool kills".
