### ISSUE TITLE
T3 Cons and T4 Cons

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#507]
We have some conflicts between T3 and T4 or T4 and T4 construction units.
We need to have a simply strategy for all players. I think, actually, it's not clear at all.

I propose to take all new cons from T4 : 
- Shield cons for Arm
- All Terrain (?) cons for Core
- Amphibious for TLL

And transform them into T3 in T3 LAB. They could make all structures (T3 MEX, Fusion, Storage, Anti T3/T4 tower, T3 NUKE and NEW T4 KBOT LAB => Shield Lab Arm, Hexapod, classic Kbot T4 Arm and Core, TLL T4)

We could lock for example the super Bantha, Krogoth, FatShrew and Exoarm with T4 RC. They could become T4.5 units. 

Then, Only T4 Cons (ship) could make the ultimate weapon (HERO LAB T5, TSAR, LOL CANON)

**Comment by skymyj** [comment]
Could be good to have T3 ehicle and Air.

**Comment by Antarac** [comment]
It's many ideas in one Issue but if i understand you right it sounds good to me.

If you wanna add more Constructors i vote yes due to #469
Every Factory Should have locked Units so i vote yes to lock some units also on T4.
To give T3 Mex to T3 Constructors and make T4 Con build TSAR etc, i vote yes.

To give Constructors shields/all terrain/amphibious ability should not be divided by factions.
Spread the abilitys among the T3 Constructors of all Factions.
For Example give Core T3 Kbot Constructor a shield (cause Core has a shield Kbot), Arm T3 Vehicle a shield and TLL something else.

**Comment by nixtux** [comment]
Ok making new t4 cons in t3 units is fine, when can you do it?

**Comment by skymyj** [comment]
I can begin this evening et f8nish tomorrow morning
