### ISSUE TITLE
Rebalance TLL Hailstorm

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#87]
Skymyj it may be balanced by cost/range/dmg, but issue is that reload time is very short.

Short reload time with long range make this unit much much more OP than Avatar.
Why?
It shoot projectiles like rain on enemy, maybe not with high damage but contstantly.
Resoult is that enemy cant avoid those projectiles.

With long reload time like on Avatar, you can expect where it will shoot again and avoid it.

_example: you cant avoid plasma from peewee, but you can avoid from hammer_

I think this unit should be rebalanced somehow.

**Comment by ksilversurfer** [comment]
maybe make range as UPG Fatboy1 with same weapon - can look amazing with short reload time.
It can be ultimate heavy plasma rain shooter.

**Comment by nixtux** [comment]
Ohh you mean more like it was when I originally added unit xD

**Comment by ksilversurfer** [comment]
I not remmeber that, propably i wasn't on spring (break time) :)
But yeah if that was the first version maybe was not bad at all :D?
(maybe just tweak damage in 1st ver.)

**Comment by nixtux** [comment]
Check old version here https://github.com/techannihilation/TA/blob/a8285b0ebf17e51a1ac311d5105add049447c24f/units/tllhailstorm.lua

**Comment by skymyj** [comment]
I understand the issue here.
We can't (I think) make a short range weapon here (fatboy at 900 range) cause, there are already unit that done this job. Take bumble T3, Riot Kbot T3, HailStorm.
This unit should be a Long range unit at +/- 4000 Range. 
Now, we can reduce the speed, damge... 

I have a good proposition to submit : Shoot at High range like Plasma Canon. Goal is to have more angleSpray and random shoot. It will add fun and more facilities to counter it.

**Comment by ksilversurfer** [comment]
just watched game with Hailstorms, they are not soo dangerous, if you build anti plasma on time.
I would only suggest to make shoots bit more random
